import img1 from "../assets/img/w1.jpg";
import img2 from "../assets/img/w2.jpg";
import img3 from "../assets/img/w3.jpg";
import img4 from "../assets/img/w4.jpg";
import img5 from "../assets/img/w5.jpg";
import img6 from "../assets/img/w6.jpg";
import img7 from "../assets/img/w7.jpg";
import img8 from "../assets/img/w8.jpg";
import img9 from "../assets/img/w9.jpg";

export default [
    {
        id: 1,
        image: img1,
        title: "Front End",
        category: "Front End",
        technologies: "Technologies ",
        divider: " ./ ",
        text_technologies: "Html, Css, Bootstrap",
        role: "Role ",
        text_role: "Front End",
        data: "Published ",
        text_data: "15 Jun 2009",
        link: "#",
    },
    {
        id: 2,
        image: img2,
        title: "IT Administration",
        category: "IT Administration",
        technologies: "Technologies ",
        divider: " ./ ",
        text_technologies: "MySql, Windows, Linux",
        role: "Role ",
        text_role: "IT Administration",
        data: "Published ",
        text_data: "15 Jun 2009",
        link: "#",
    },
    {
        id: 3,
        image: img3,
        title: "Back End",
        category: "Back End",
        technologies: "Technologies ",
        divider: " ./ ",
        text_technologies: "React, JavaScript, Python",
        role: "Role ",
        text_role: "Back End",
        data: "Published ",
        text_data: "05 May 2014",
        link: "#",
    },
    {
        id: 4,
        image: img4,
        title: "IT Administration",
        category: "IT Administration",
        technologies: "Technologies ",
        divider: " ./ ",
        text_technologies: "MySql, Windows, Linux",
        role: "Role ",
        text_role: "IT Administration",
        data: "Published ",
        text_data: "15 Jun 2009",
        link: "#",
    },
    {
        id: 5,
        image: img5,
        title: "Back End",
        category: "Back End",
        technologies: "Technologies ",
        divider: " ./ ",
        text_technologies: "React, JavaScript, Python",
        role: "Role ",
        text_role: "Back End",
        data: "Published ",
        text_data: "05 May 2014",
        link: "#",
    },
    {
        id: 6,
        image: img6,
        title: "Front End",
        category: "Front End",
        technologies: "Technologies ",
        divider: " ./ ",
        text_technologies: "Html, Css, Bootstrap",
        role: "Role ",
        text_role: "Front End",
        data: "Published ",
        text_data: "15 Jun 2009",
        link: "#",
    },
    {
        id: 7,
        image: img7,
        title: "Front End",
        category: "Front End",
        technologies: "Technologies ",
        divider: " ./ ",
        text_technologies: "Html, Css, Bootstrap",
        role: "Role ",
        text_role: "Front End",
        data: "Published ",
        text_data: "15 Jun 2009",
        link: "#",
    },
    {
        id: 8,
        image: img8,
        title: "IT Administration",
        category: "IT Administration",
        technologies: "Technologies ",
        divider: " ./ ",
        text_technologies: "MySql, Windows, Linux",
        role: "Role ",
        text_role: "IT Administration",
        data: "Published ",
        text_data: "15 Jun 2009",
        link: "#",
    },
    {
        id: 9,
        image: img9,
        title: "Back End",
        category: "Back End",
        technologies: "Technologies ",
        divider: " ./ ",
        text_technologies: "React, JavaScript, Python",
        role: "Role ",
        text_role: "Back End",
        data: "Published ",
        text_data: "05 May 2014",
        link: "#",
    },
]